services:
  pgsql:
    container_name: book-db
    build:
      context: .
      dockerfile: Dockerfile.pg-ko
      args:
        PG_MAJOR: "16"
    image: my-postgres:ko
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: book
      TZ: Asia/Seoul
    volumes:
      - postgres-book-data:/var/lib/postgresql/data
    command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr" ]

  redis:
    container_name: book-redis
    image: redis:8
    ports:
      - "6379:6379"
    environment:
      TZ: Asia/Seoul
      REDIS_ARGS: "--requirepass systempass"
    volumes:
      - redis-book-data:/data

volumes:
  postgres-book-data:
  redis-book-data: